/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aiproject;

import com.opencsv.CSVReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

/**
 *
 * @author panch
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.displayMovie_1.setEditable(false);
        this.displayMovie_2.setEditable(false);
        this.displayMovie_3.setEditable(false);
        this.goUp.setEnabled(false);
        
        movies = new ArrayList<>();
        displaying = new ArrayList<>();
        try {
            data();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.Initialshow();
    }
    ArrayList<Movie> movies;
    List<Movie> displaying;
    int left = 0;
    int center = 1;
    int right = 2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayMovie_1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayMovie_2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayMovie_3 = new javax.swing.JTextArea();
        goUp = new javax.swing.JButton();
        goDown = new javax.swing.JButton();
        likeBtn1 = new javax.swing.JButton();
        likeBtn2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dislikeBtn1 = new javax.swing.JButton();
        dislikeBtn2 = new javax.swing.JButton();
        dislikeBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("MOVIE RECOMMENDER 1.0");

        displayMovie_1.setColumns(20);
        displayMovie_1.setRows(5);
        jScrollPane2.setViewportView(displayMovie_1);

        displayMovie_2.setColumns(20);
        displayMovie_2.setRows(5);
        jScrollPane1.setViewportView(displayMovie_2);

        displayMovie_3.setColumns(20);
        displayMovie_3.setRows(5);
        jScrollPane3.setViewportView(displayMovie_3);

        goUp.setText("↑");
        goUp.setToolTipText("Scroll Up");
        goUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goUpActionPerformed(evt);
            }
        });

        goDown.setText("↓");
        goDown.setToolTipText("Scroll Down");
        goDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goDownActionPerformed(evt);
            }
        });

        likeBtn1.setText("\t👍");
        likeBtn1.setToolTipText("Like");

        likeBtn2.setText("\t👍");
        likeBtn2.setToolTipText("Like");

        jButton1.setText("\t👍");
        jButton1.setToolTipText("Like");

        dislikeBtn1.setText("👎");
        dislikeBtn1.setToolTipText("Dislike");

        dislikeBtn2.setText("👎");
        dislikeBtn2.setToolTipText("Dislike");

        dislikeBtn3.setText("👎");
        dislikeBtn3.setToolTipText("Dislike");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(likeBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dislikeBtn1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(likeBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dislikeBtn2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(goDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dislikeBtn3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(goUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goDown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(likeBtn1)
                        .addComponent(dislikeBtn1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(likeBtn2)
                        .addComponent(dislikeBtn2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(dislikeBtn3)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goDownActionPerformed
        if(left == 0){
            this.goUp.setEnabled(true);
        }
        left+=3;
        center+=3;
        right+=3;
        if(left <=this.displaying.size()){
            this.displayMovie_1.setText(this.displaying.get(left).toString());
        }
        if(center <= this.displaying.size()){
            this.displayMovie_2.setText(this.displaying.get(center).toString());
        }
        if(right <= this.displaying.size()){
            this.displayMovie_3.setText(this.displaying.get(right).toString());
        }
        if(left == this.displaying.size()||center == this.displaying.size()||right == this.displaying.size()){
            this.goDown.setEnabled(false);
        }
    }//GEN-LAST:event_goDownActionPerformed

    private void goUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goUpActionPerformed
        
        left-=3;
        center-=3;
        right-=3;
        if(left <=this.displaying.size()){
            this.displayMovie_1.setText(this.displaying.get(left).toString());
        }
        if(center <= this.displaying.size()){
            this.displayMovie_2.setText(this.displaying.get(center).toString());
        }
        if(right <= this.displaying.size()){
            this.displayMovie_3.setText(this.displaying.get(right).toString());
        }
        if(left == 0){
            this.goUp.setEnabled(false);
        }
    }//GEN-LAST:event_goUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>                    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });       
        
    }
    void data () throws FileNotFoundException, IOException{
        ArrayList<Movie> data = new ArrayList<>();
        CSVReader reader = new CSVReader(new FileReader("C:/IA/AIProject/data/Data_Proyecto.csv"));
        List<String[]> lines = reader.readAll();
        for(int i = 1; i<lines.size(); i++){
            data.add(new Movie(lines.get(i)));
        }
        var sort = new ArrayList<Movie>();
        for(int i = 0; i < data.size();i++){
            var temp = data.get(i);
            if(sort.stream().filter(x -> x.title.equals(temp.title)).count()==0){
                sort.add(temp);
            }
        }
        this.movies = sort;
    }
    void Initialshow(){
        sampling samples = new sampling();
        //this.displaying = this.movies.stream().sorted(Comparator.comparing(Movie::getIMDB_Score).reversed()).collect(Collectors.toList());
        samples.Sampling(this.movies);
        this.movies = samples.CalculatePMovies(this.movies);
        this.displaying = movies.stream().sorted(Comparator.comparing(Movie::getLikeliness).reversed()).collect(Collectors.toList());
        
        this.displayMovie_1.setText(this.displaying.get(0).toString());
        this.displayMovie_2.setText(this.displaying.get(1).toString());
        this.displayMovie_3.setText(this.displaying.get(2).toString());        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dislikeBtn1;
    private javax.swing.JButton dislikeBtn2;
    private javax.swing.JButton dislikeBtn3;
    private javax.swing.JTextArea displayMovie_1;
    private javax.swing.JTextArea displayMovie_2;
    private javax.swing.JTextArea displayMovie_3;
    private javax.swing.JButton goDown;
    private javax.swing.JButton goUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton likeBtn1;
    private javax.swing.JButton likeBtn2;
    // End of variables declaration//GEN-END:variables
}
